# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""Generate the fixed logical module contract for a compiled native adapter."""

import argparse
import json
import os
import tempfile
from collections.abc import Sequence
from pathlib import Path
from typing import cast

from _therock_utils.gpu_targets import Vendor
from _therock_utils.module_contract import RunnerDescription, runner_description


def render_header(description: RunnerDescription) -> str:
    contract = description.contract
    # JSON string escaping is valid for these ASCII C++ string constants. No
    # caller-provided C++ fragments or raw-string delimiters enter the header.
    description_json = json.dumps(
        description.record(), sort_keys=True, separators=(",", ":")
    )
    return "\n".join(
        (
            "// Generated by configure_module_contract.py; compiled adapter metadata.",
            "#pragma once",
            "",
            "namespace therock::module_contract {",
            f"inline constexpr char kContractAbi[] = {json.dumps(contract.abi)};",
            f"inline constexpr unsigned kContractVersion = {contract.version};",
            f"inline constexpr char kContractSha256[] = {json.dumps(contract.sha256)};",
            f"inline constexpr unsigned kGroupSize = {contract.launch.block[0]};",
            f"inline constexpr unsigned kPointerBits = {contract.pointer_bits};",
            f"inline constexpr char kRunnerDescription[] = {json.dumps(description_json)};",
            "}  // namespace therock::module_contract",
            "",
        )
    )


def configure_contract(
    vendor: Vendor, header_path: Path, description_path: Path
) -> None:
    """Generate stable files; replacements are atomic per file, not as a pair."""
    description = runner_description(vendor)
    if header_path.resolve() == description_path.resolve():
        raise ValueError("Header and description outputs must be distinct")
    documents = (
        (header_path, render_header(description)),
        (
            description_path,
            json.dumps(description.record(), indent=2, sort_keys=True) + "\n",
        ),
    )
    staged: list[tuple[Path, Path]] = []
    try:
        for destination, contents in documents:
            if (
                destination.exists()
                and destination.read_text(encoding="utf-8") == contents
            ):
                continue
            destination.parent.mkdir(parents=True, exist_ok=True)
            with tempfile.NamedTemporaryFile(
                mode="w",
                encoding="utf-8",
                newline="\n",
                dir=destination.parent,
                prefix=f".{destination.name}.",
                delete=False,
            ) as file:
                temporary = Path(file.name)
                staged.append((temporary, destination))
                file.write(contents)
        for temporary, destination in staged:
            os.replace(temporary, destination)
    finally:
        for temporary, _ in staged:
            temporary.unlink(missing_ok=True)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vendor", choices=("amd", "nvidia", "intel"), required=True)
    parser.add_argument("--header", type=Path, required=True)
    parser.add_argument("--description", type=Path, required=True)
    args = parser.parse_args(argv)
    try:
        configure_contract(cast(Vendor, args.vendor), args.header, args.description)
    except (ValueError, OSError) as exc:
        parser.error(str(exc))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
