# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""Generate target selections for TheRock's experimental multi-vendor profile.

The manifest describes requested targets only. It is neither build provenance nor
hardware qualification evidence, and possible payload formats are not a list of
artifacts produced by a build.
"""

import argparse
import json
import os
import tempfile
from collections.abc import Iterable, Sequence
from pathlib import Path

from _therock_utils.gpu_targets import GpuTarget, parse_gpu_targets


def render_cmake(targets: tuple[GpuTarget, ...]) -> str:
    """Render only parser-validated identifiers into a CMake include."""
    lines = [
        "# Generated by configure_multi_vendor.py; target selections only.",
        "# Selection does not establish compiler support or hardware qualification.",
        'set(THEROCK_MULTI_VENDOR_TARGET_KEYS "'
        + ";".join(t.slug for t in targets)
        + '")',
    ]
    for target in targets:
        prefix = f"THEROCK_MULTI_VENDOR_{target.slug}"
        fields = (
            ("ID", target.canonical_id),
            ("VENDOR", target.vendor),
            ("BACKEND", target.backend),
            ("PROCESSOR", target.processor),
            ("HIP_PLATFORM", target.cmake_hip_platform),
            ("HIP_ARCHITECTURE", target.cmake_hip_architecture),
            ("COMPILER_TARGET", target.compiler_target),
        )
        for name, value in fields:
            # All nonempty values come from GpuTarget's closed identifier
            # grammar. Quotes, semicolons, backslashes and variable references
            # cannot occur; None means the toolchain owns target selection.
            lines.append(f'set({prefix}_{name} "{value or ""}")')
    return "\n".join(lines) + "\n"


def render_manifest(targets: tuple[GpuTarget, ...]) -> str:
    """Record canonical selection data without inventing validation evidence."""
    manifest = {
        "schema_version": 1,
        "kind": "target-selection",
        "targets": [
            {
                "id": target.canonical_id,
                "slug": target.slug,
                "vendor": target.vendor,
                "backend": target.backend,
                "processor": target.processor,
                "features": [
                    {"name": feature.name, "enabled": feature.enabled}
                    for feature in target.features
                ],
                "cmake_hip_platform": target.cmake_hip_platform,
                "cmake_hip_architecture": target.cmake_hip_architecture,
                "compiler_target": target.compiler_target,
                "payload_types": list(target.payload_types),
                "experimental": target.experimental,
                "qualification": "unvalidated",
            }
            for target in targets
        ],
    }
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def configure_targets(target_ids: Iterable[str], output_dir: Path) -> tuple[Path, Path]:
    """Validate a selection, then emit targets.cmake and gpu_targets.json.

    Input order is preserved. Invalid or duplicate targets leave the destination
    untouched. Both complete files are staged before replacing either output;
    replacement is atomic per file, not a transaction spanning both files.
    """
    targets = parse_gpu_targets(target_ids)
    if not targets:
        raise ValueError("At least one GPU target is required")
    documents = (
        (output_dir / "targets.cmake", render_cmake(targets)),
        (output_dir / "gpu_targets.json", render_manifest(targets)),
    )
    output_dir.mkdir(parents=True, exist_ok=True)
    staged: list[tuple[Path, Path]] = []
    try:
        for destination, contents in documents:
            with tempfile.NamedTemporaryFile(
                mode="w",
                encoding="utf-8",
                newline="\n",
                dir=output_dir,
                prefix=f".{destination.name}.",
                suffix=".tmp",
                delete=False,
            ) as temp:
                temporary = Path(temp.name)
                staged.append((temporary, destination))
                temp.write(contents)
        for temporary, destination in staged:
            os.replace(temporary, destination)
    finally:
        for temporary, _ in staged:
            temporary.unlink(missing_ok=True)
    return documents[0][0], documents[1][0]


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--targets",
        nargs="+",
        required=True,
        metavar="VENDOR:BACKEND:PROCESSOR",
        help="Canonical GPU target IDs, optionally including AMD feature suffixes",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Directory for targets.cmake and gpu_targets.json",
    )
    args = parser.parse_args(argv)
    try:
        configure_targets(args.targets, args.output_dir)
    except (ValueError, OSError) as exc:
        parser.error(str(exc))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
